### ISSUE TITLE
Return previous instruction for connection on linux

### ISSUE THREAD

**Issue by bashkos** [Jigsaw-Code/outline-releases#34]
Why you changed connection instruction for linux? Shadowsocks-Qt5 don't kept stable connection. Previous method was better. Please, return it. Or provide a choice.

**Comment by radigost** [comment]
I cannot connect with new connection instruction for linux, after update, this new Shadowsocks-Qt5 isn't connecting. for other systems everything is ok(except Android app - it is eating battery as hell)

**Comment by trevj** [comment]
@bashkos Thanks for trying Outline. We felt Shadowsocks-Qt5 was more likely to be more useable by more users than the previous command-line instructions. FYI, we are working on our own Linux client which would obviously supercede both.
