### ISSUE TITLE
No client release for MacOS?

### ISSUE THREAD

**Issue by eddyw** [Jigsaw-Code/outline-releases#48]
I can't download from the App store in China since Outline is .. well blocked in the App store. Is it possible to provide a MacOS .pkg client?

**Comment by trevj** [comment]
@eddyw Thanks for trying Outline. This has been asked before - I'm afraid it's not possible to distribute the macOS client application outside of the App Store:
https://github.com/Jigsaw-Code/outline-client/issues/148
