### ISSUE TITLE
how to add two VPS?

### ISSUE THREAD

**Issue by suonli** [Jigsaw-Code/outline-releases#8]
I have banwagon and google cloud. both working,but can only manger one VPS?

**Comment by sandrigo** [comment]
If you've set up Outline on both cloud providers, you can toggle between them by simply going to the 'Settings' gear and 'Forget'ting the server. This will not delete the server, but simply clear your credentials to access it. 

Then, you can go into 'Advanced Mode' and paste the output of whichever one of the two cloud servers you've created in the 2nd step of the installation process. You can switch back and forth this way. This obviously requires that you have captured and stored the output of the installation process on both cloud providers.

This is a workaround, of course. If it becomes a common enough use case, we can work on a better UI for this.

**Comment by thelonious89** [comment]
Yes, common use case.
