### ISSUE TITLE
Outline Client for Windows Doesn't Works on Some Browsers

### ISSUE THREAD

**Issue by irfanfadilah** [Jigsaw-Code/outline-releases#9]
I tried the latest Outline Client for Windows 10 but cannot make it works on Google Chrome and Mozilla Firefox, I tried Opera and it's works fine. I couldn't find this issue on Outline's Help page.

So is there any additional steps to make it works on all applications (especially browsers)?

**Comment by bemasc** [comment]
The Outline Client for Windows is intended to be compatible with Chrome and Firefox.  Do you have any proxy extensions installed in Chrome or Firefox?   A proxy extension could be overriding the system-wide proxy setting that Outline sets.

**Comment by irfanfadilah** [comment]
I see, I have a proxy extension. After disabling the extension, it's works.
Also, it might be a good idea to put this on Outline's Help/FAQ page.

Thank you for the help, @bemasc!
